version: "3.5"
services:

  redis:
    image: redis:7-alpine
    container_name: omniflow-redis
    ports:
      - "6379:6379"
    restart: always

  # 1. Prometheus (数据采集)
  prometheus:
    image: prom/prometheus:latest
    container_name: omniflow-prometheus
    volumes:
      - ./config/prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway" # 允许容器访问宿主机 (因为你的 Go 代码是在本机跑的)

  # 2. Grafana (数据展示)
  grafana:
    image: grafana/grafana:latest
    container_name: omniflow-grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # 登录密码
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

  # --- 业务数据库 (MySQL) ---
  mysql:
    image: mysql:8.0
    container_name: omniflow-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=omniflow
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # --- Temporal 数据库 (PostgreSQL) ---
  postgresql:
    image: postgres:12
    container_name: temporal-postgres
    environment:
      - POSTGRES_USER=temporal
      - POSTGRES_PASSWORD=temporal
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # --- Temporal Server ---
  temporal:
    image: temporalio/auto-setup:latest
    container_name: temporal-server
    ports:
      - "7233:7233"
      - "8233:8233"
    environment:
      - DB=postgres12
      - DB_PORT=5432
      - POSTGRES_USER=temporal
      - POSTGRES_PWD=temporal
      - POSTGRES_SEEDS=postgresql
      - SKIP_DEFAULT_NAMESPACE_CREATION=false
    depends_on:
      - postgresql

  temporal-ui:
    image: temporalio/ui:latest
    container_name: temporal-ui
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    ports:
      - "8080:8080"
    depends_on:
      - temporal

volumes:
  postgres_data:
  mysql_data:

